
package com.form;

import com.ManejoBasesDeDatos.Querys;
import java.util.List;


/**
 *
 * @author kelvi
 * 
 */
public class Form_Clase extends javax.swing.JPanel {

    private String NoCuenta;
    private int i;
    private Querys querys;
    
    private void initTableClases() {
        if(i == 0)
        {
            
        }
        else
        {
            List<Object[]> cls = querys.selectCursandoByEstudiante(NoCuenta);
            
            for(Object[] c : cls)
            {
                table1.addRow(c);
            }
        }
        
    }
    public Form_Clase(String NoCuenta, int i) {
        initComponents();
        
        this.NoCuenta = NoCuenta;
        this.i = i;
        
        table1.fixTable(jScrollPane1);
        querys = new Querys();
        
        if(i == 1)
        {
            table1.getColumnModel().getColumn(2).setHeaderValue("Seccion");
        }
        
        initTableClases();
        
        setOpaque(false);
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.swing.table.Table();
        lblDir = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Creditos", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        lblDir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDir.setForeground(new java.awt.Color(102, 51, 255));
        lblDir.setText("Clases / Todas las Clases");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDir;
    private com.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
